# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    app.googleClient.scope: ['https://www.googleapis.com/auth/gmail.send']

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.googleClient:
      class: AppBundle\Services\GoogleClientService
      arguments: ['%app.googleClient.scope%']


    app.gmail:
      class: AppBundle\Services\GmailService
      arguments: ['@app.googleClient']
